/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OpponentFrame.java
 *
 * Created on Jul 19, 2010, 1:36:30 PM
 */

package dooz;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.RandomAccessFile;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author SONY
 */
public class OpponentFrame extends javax.swing.JFrame {

    private OpponentAgent opAgent;


    /** Creates new form OpponentFrame */
    public OpponentFrame(OpponentAgent oa)
    {
        initComponents();

        opAgent=oa;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Log_TxtArea = new javax.swing.JTextArea();
        NumberOfLearnsLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Opponent Agent");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Opponent Agent");

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Log_TxtArea.setColumns(20);
        Log_TxtArea.setRows(5);
        jScrollPane1.setViewportView(Log_TxtArea);

        NumberOfLearnsLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        NumberOfLearnsLabel.setForeground(new java.awt.Color(255, 51, 51));
        NumberOfLearnsLabel.setText("000");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13));
        jLabel3.setText("I Have Learned");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13));
        jLabel4.setText("Ways .");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OpAgent.png"))); // NOI18N

        jMenu1.setText("Configure KnowledgeBase");

        jMenuItem1.setText("Load Knowledge Base");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Save Knowledge Base");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumberOfLearnsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(NumberOfLearnsLabel)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addGap(51, 51, 51)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        // Load
        try
        {
            JFileChooser jfc=new JFileChooser(new File(".").getCanonicalPath());
            jfc.showOpenDialog(null);
            if(jfc.getSelectedFile()!=null)
            {
                RandomAccessFile raf=new RandomAccessFile(jfc.getSelectedFile(), "rws");
                
                while(true)
                {
                    String line="";
                    try
                    {
                        line=raf.readLine();
                    }
                    catch(Exception ex)
                    {
                        break;
                    }
                    if(line==null || line.trim().length()==0) break;

                    String[] infos=line.split(",");
                    Vector<Integer> vec=new Vector<Integer>();
                    for(int i=0;i<infos.length-1;i++)
                    {
                        vec.add(Integer.parseInt(infos[i]));
                    }
                    
                    opAgent.addDistinct2Wins(vec, Boolean.parseBoolean(infos[infos.length-1]));
                }
                
                
                
                JOptionPane.showMessageDialog(rootPane, "Opponenet's KnowledgeBase Was Loaded And Added Successfully ...","Load",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        // Save
        try
        {
            JFileChooser jfc=new JFileChooser(new File(".").getCanonicalPath());
            jfc.showSaveDialog(null);
            if(jfc.getSelectedFile()!=null)
            {
                FileWriter output=new FileWriter(jfc.getSelectedFile());
                
                for(int i=0;i<opAgent.getWins().size();i++)
                {
                    output.write(opAgent.getWins().elementAt(i).toString());
                    
                    // it means enter
                    output.write(13);
                    output.write(10);
                }
                
                output.flush();
                output.close();
                
                JOptionPane.showMessageDialog(rootPane, "Opponenet's KnowledgeBase Was Saved Successfully ...","Save",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void addLog(String s)
    {
        String tmp=Log_TxtArea.getText()+"\n"+s;
        Log_TxtArea.setText(tmp);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpponentFrame(new OpponentAgent()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Log_TxtArea;
    public javax.swing.JLabel NumberOfLearnsLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
